### ISSUE TITLE
Necessary IAM permissions

### ISSUE THREAD

**Issue by billbarni** [DarkAtra/feign-aws-sigv4#109]
**Is your feature request related to a problem? Please describe.**
Some small tutorial on what kind of configuration I need to set in AWS for the calls to work.
I got the IAM Lambda Function invoke permission in a java app in a container in aws eks. But the Java app uses Feign (your interceptor) to call a Python Rest endpoint in Lambda, so that permission is not enough... Is there some HTTP request permission also required?

Sorry to bother with this.

It's would be more of a "how to configure a test in AWS that works for real".

**Comment by DarkAtra** [comment]
@billbarni you can have a look at the [integration tests](https://github.com/DarkAtra/feign-aws-sigv4/blob/main/integration-tests/infrastructure/main.ts#L121) folder. it contains a full setup that i use to test the interceptor (e.g. it also contains an iam role with the appropriate permissions).
